SITEMAP_FILENAMES = [
    "/",
    "/about.html",
    "/cv.html",
    "/interests/",
    "/interests/intro_to_logs.pdf",
    "/interests/maths-problems/",
    "/interests/maths-problems/problem-1/",
    "/interests/maths-problems/problem-1/solution.pdf",
    "/interests/maths-problems/problem-2/",
    "/interests/maths-problems/problem-2/solution.pdf",
    "/interests/maths-problems/problem-3/",
    "/interests/maths-problems/problem-3/solution.pdf",
    "/interests/skiing.html",
    "/projects/",
    "/projects/building-this-website/",
    "/projects/building-this-website/approach.html",
    "/projects/building-this-website/awg.html",
    "/projects/building-this-website/dns.html",
    "/projects/my-setup.html",
    "/projects/ski-tripper.html",
    "/research/",
    "/research/ica_extensions_pt1.pdf",
    "/research/ica_introduction.pdf",
    "/research/thesis.pdf",
]