[[WIP_PAGES]]
name = "Professional career"
url = "/cv/index.html"

[[WIP_PAGES]]
name = "My tastes"
url = "/my-tastes/index.html"

[[WIP_PAGES]]
name = "Publications"
url = "/publications/index.html"
