MY_CAREER_SUMMARY = "TODO copy from LinkedIn"

[[MY_EDUCATION]]
degree = "DPhil (Ph.D) in Explanation from Artificial Neural Networks"
time = "1998"
institution = "University of Oxford."
details = [
    "Algorithms to derive human interpretable and quantifiably trustworthy explanations from general purpose probability estimators.",
    "CASE award from Rolls Royce."
]

[[MY_EDUCATION]]
degree = "BA, MA in Engineering and Computing Science"
time = "1995"
institution = "University of Oxford."
details = [
    "First class (1st) Honours.",
    "Academic Scholar throughout.",
    "Faculty project prize for multi-processor simulation of small mobile robot."
]

[[MY_EDUCATION]]
degree = "A levels"
time = "1980 - 1991"
institution = "Haberdashers' Aske's School, Elstree."
details = [
    "A levels in Maths, Further Maths, Physics, Electronics (4 A's)."
]


[[MY_EXPERIENCE]]
job_title = "Independent AI Researcher and board member/advisor"
time = "2026 - Present"
company = "Freelance"
details = [
    "Only interested in part-time/contract work which is challenging, stimulating, and mutually beneficial."
]

[[MY_EXPERIENCE]]
job_title = "Chief Technology Officer"
time = "2021 - 2025"
company = "Aixial"
details = [
    "Responsible for integration and structural changes following acquisition.",
    "Negotiated the orderly exit from multiple client and vendor contracts.",
    "Advised senior executive team.",
    "Set the AI strategy."
]

[[MY_EXPERIENCE]]
job_title = "Chief Technology Officer"
time = "2002 - 2021"
company = "Cmed Group"
details = [
    "Designed, built, and supported the technology which collected data from tens of thousands of subjects across ~1000 clinical trials, delivering regulatory compliant results for ~150 customers ranging from top-ten Pharmaceutical companies to much smaller innovative Biotech.",
    "Ran private cloud of multi-level redundant virtualised data centre servers (~500), later migrated to public cloud (AWS, Azure).",
    "Unique features included eSource, built-in Analytics (R, Python), Actionable Visualisations (tech to the data), zero downtime.",
    "All backed by unavoidable audit trail over single source of truth (<a href=\"https://patents.google.com/patent/US20040177090A1/\">patent US20040177090A1</a>).",
    "Early adoptor of Python for all server-side infrastructure/code.",
    "Responsible for all R&D, System Support, and Corporate IT.",
    "Head of SaaS Business Unit, responsible for sales, marketing, and financial forecasts.",
    "The external and internal figurehead for all Technology innovation.",
    "A key leader and board member for the group."
]

[[MY_EXPERIENCE]]
job_title = "Co-founder and Chief Technology Officer"
time = "2000 - 2002"
company = "ThirdPhase Ltd"
details = [
    "Responsible for all technology development and the design of innovative clinical trial system architecture (<a href=\"https://patents.google.com/patent/US20040025030A1/\">patent US20040025030A1</a>).",
    "Significantly involved in the raising of venture capital and the public face of the company.",
    "ThirdPhase was then acquired and became Cmed Technology, a subsidiary of Cmed Group."
]

[[MY_EXPERIENCE]]
job_title = "Software Engineer"
time = "1999 - 2000"
company = "Freelance"
details = [
    "Built a prototype e-commerce system utilising encryption technologies. This integrated peripheral hardware including fingerprint devices, mobile phones, barcode scanners and printers, ECG, vital signs and spirometry medical devices.",
    "Produced fully working demo system in 3 months.",
    "Successfully pitched for fund-raising to create ThirdPhase Ltd."
]

[[MY_EXPERIENCE]]
job_title = "Research Assistant"
time = "1998 - 1999"
company = "Department of Engineering Science, University of Oxford"
details = [
    "College Lecturer in Engineering.",
    "Applying non-linear dynamical methods and Independent Component Analysis (ICA) to novelty detection in time-series data, and for the visualisation and analysis of ECG and EEG traces."
]
